// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buoablhkbfctwmjzeisk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1b2FibGhrYmZjdHdtanplaXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDE0OTksImV4cCI6MjA3NDIxNzQ5OX0.lixczHtEa6inBt5pfQR2ZzKp1_ZtKreOOhKCY6tKkUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});